@{
    # Module manifest for module 'GripDevJsonSchemaValidator'
    # Generated by: YourName
    # Generated on: 2023-04-01

    # Script module or binary module file associated with this manifest.
    RootModule = 'GripDevJsonSchemaValidator.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # ID used to uniquely identify this module
    GUID = '12345678-1234-1234-1234-123456789012'

    # Author of this module
    Author = 'YourName'

    # Company or vendor of this module
    CompanyName = 'YourCompany'

    # Copyright statement for this module
    Copyright = '(c) 2023 YourCompany. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'A Powershell module for running Newtonsoft schema validation on input JSON schema and files to validate.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @('Newtonsoft.Json.dll', 'Newtonsoft.Json.Schema.dll')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = @('Test-JsonSchema')

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @()

    # DSC resources to export from this module
    DscResourcesToExport = @()

    # List of all modules packaged with this module
    ModuleList = @()

    # List of all files packaged with this module
    FileList = @('GripDevJsonSchemaValidator.psm1', 'Newtonsoft.Json.dll', 'Newtonsoft.Json.Schema.dll')

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{}

    # HelpInfo URI of this module
    HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = ''
}
