name: Build, Test, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore
        working-directory: src/NewtonsoftJsonSchemaTool

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src/NewtonsoftJsonSchemaTool

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: src/NewtonsoftJsonSchemaTool

      - name: Publish CLI tool
        run: dotnet pack --configuration Release --output ./nupkg
        working-directory: src/NewtonsoftJsonSchemaTool

      - name: Upload CLI tool to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./nupkg/NewtonsoftJsonSchemaTool.1.0.0.nupkg
          asset_name: NewtonsoftJsonSchemaTool.1.0.0.nupkg
          asset_content_type: application/zip

      - name: Publish Powershell module to Powershell Gallery
        run: |
          Install-Module -Name PowerShellGet -Force -SkipPublisherCheck
          Publish-Module -Path ./src/NewtonsoftJsonSchemaTool -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
