name: Build, Test, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: script/test

      - name: Publish CLI tool
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Increment version
        id: increment_version
        shell: pwsh
        run: |
          $moduleManifest = Import-PowerShellDataFile ./GripDevJsonSchemaValidator/GripDevJsonSchemaValidator.psd1
          $currentVersion = [Version]$moduleManifest.ModuleVersion
          $newVersion = "{0}.{1}.{2}" -f $currentVersion.Major, $currentVersion.Minor, $env:GITHUB_RUN_NUMBER
          Update-ModuleManifest -Path ./GripDevJsonSchemaValidator/GripDevJsonSchemaValidator.psd1 -ModuleVersion $newVersion
          
          $csprojFile = Get-Content ./GripDevJsonSchemaValidator.csproj
          $csprojFile = $csprojFile -replace '<Version>([0-9]+\.[0-9]+\.[0-9]+)</Version>', "<Version>$newVersion</Version>"
          Set-Content ./GripDevJsonSchemaValidator.csproj $csprojFile

      - name: Publish NuGet package
        if: github.ref == 'refs/heads/main'
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish Powershell module to Powershell Gallery
        shell: pwsh
        run: |
          Install-Module -Name PowerShellGet -Force -SkipPublisherCheck
          Publish-Module -Path ./GripDevJsonSchemaValidator -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
